# Generated by Django 2.2.7 on 2019-12-14 23:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer_name', models.CharField(max_length=100)),
                ('summary', models.TextField(help_text='Enter a brief description of the producer', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the product', max_length=1000)),
                ('isbn', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN')),
                ('photo', models.ImageField(upload_to='')),
                ('producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Producer')),
            ],
        ),
        migrations.CreateModel(
            name='Type_of_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Type of product (e.g. smartphone, TV etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular product across whole shop', primary_key=True, serialize=False)),
                ('characteristics', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, choices=[('w', 'Will be soon'), ('i', 'In the way'), ('o', 'Delivered'), ('a', 'Available'), ('s', 'Sold')], default='w', help_text='Product availability', max_length=1)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Product')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='type_of_product',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='shop.Type_of_product'),
        ),
    ]
