# Generated by Django 2.2.7 on 2019-12-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['status']},
        ),
        migrations.AlterModelOptions(
            name='productinstance',
            options={},
        ),
        migrations.RemoveField(
            model_name='productinstance',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('w', 'Will be soon'), ('i', 'In the way'), ('o', 'Delivered'), ('a', 'Available'), ('s', 'Sold')], default='w', help_text='Product availability', max_length=1),
        ),
    ]
