# Generated by Django 2.2.7 on 2019-12-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191215_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('w', 'Waiting'), ('a', 'Available')], default='w', help_text='Book availability', max_length=1),
        ),
    ]
