# Generated by Django 2.2.7 on 2019-12-15 20:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Enter number of physical objects'),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(help_text='Select photo of the book', upload_to=''),
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
    ]
