# Generated by Django 2.2.7 on 2019-12-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20191216_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(default='default.jpg', help_text='Select photo of the book', upload_to=''),
        ),
    ]
