# Generated by Django 2.2.7 on 2019-12-18 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_bookinorder_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.DeleteModel(
            name='BookInOrder',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
