# Generated by Django 2.2.7 on 2019-12-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20191222_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
